version: 0.0
Resources:
  - fetch_order:
      Type: AWS::Lambda::Function
      Properties:
        Name: "fetch_order"
        Alias: "latest"
        CurrentVersion: "<CURRENT_VERSION>"
        TargetVersion: "<PUBLISHED_VERSION>"
  - save_order:
      Type: AWS::Lambda::Function
      Properties:
        Name: "save_order"
        Alias: "latest"
        CurrentVersion: "<CURRENT_VERSION>"
        TargetVersion: "<PUBLISHED_VERSION>"
Hooks:
  - BeforeAllowTraffic: "check-before-allow-traffic"
  - AfterAllowTraffic: "check-after-allow-traffic"
