version: 0.2
Resources:
  - OrderServiceFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "<LAMBDA_FUNCTION_NAME>"
        Alias: "latest"
        CurrentVersion: "<CURRENT_VERSION>"
        TargetVersion: "<PUBLISHED_VERSION>"
Hooks:
  BeforeAllowTraffic:
    - Location: "check-before-allow-traffic"
      Type: "Lambda"
      Timeout: 300
  AfterAllowTraffic:
    - Location: "check-after-allow-traffic"
      Type: "Lambda"
      Timeout: 300